FROM node:latest

RUN mkdir /front

RUN npm install nodemon -g

WORKDIR /front
ADD app/package.json /front/package.json
RUN npm install

ADD app/nodemon.json /front/nodemon.json

EXPOSE 3000

CMD npm start