FROM node:latest

RUN mkdir /front

RUN npm install nodemon -g

WORKDIR /front
ADD front/package.json /front/package.json
RUN npm install

ADD front/nodemon.json /front/nodemon.json

EXPOSE 8080

CMD npm start