frontend:
  dockerfile: Dockerfile-frontend
  build: ./
  ports:
   - "8080:8080"
  volumes:
    - "app:/front"

backend:
  dockerfile: ./Dockerfile-backend
  build: ./
  ports:
   - "3000:3000"
  volumes:
    - "app:/back"

neo4j:
  image: tpires / neo4j
  ports:
    - "7474:7001"

mysql:
  image: wnameless / mysql-phpmyadmin
  ports:
    - "3306:7002"

qgis:
  image: opengisch / qgis-server-webclient
  ports:  
  - "80:7003"  

jsonServer:
  image: clue/json-server:latest
    - "80:7004"