FROM node:latest

RUN mkdir /back

RUN npm install nodemon -g

WORKDIR /src
ADD app/package.json /back/package.json
RUN npm install

ADD app/nodemon.json /back/nodemon.json

EXPOSE 3000

CMD npm start